import{a as L,S as w,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const b="50757194-f2b273e514caa2f992e1a47fc",m=async(e,r=1,a=15)=>{try{return(await L.get("https://pixabay.com/api/",{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data.hits}catch(o){throw console.error("Error fetching data:",o),o}};let u;const y=e=>{const r=document.querySelector(".gallery"),a=e.map(o=>`
        <li class="gallery-item">
            <a href="${o.largeImageURL}" class="lightbox">
                <img src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class="image-info">
                <p><strong>Likes</strong> ${o.likes}</p>
                <p><strong>Views</strong> ${o.views}</p>
                <p><strong>Comments</strong> ${o.comments}</p>
                <p><strong>Downloads</strong> ${o.downloads}</p>
            </div>
        </li>
    `).join("");r.innerHTML+=a,u?u.refresh():u=new w(".gallery a",{captionsData:"alt",captionDelay:250})},v=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},p=()=>{const e=document.querySelector(".loader");e.style.display="block"},h=()=>{const e=document.querySelector(".loader");e.style.display="none"},f=()=>{document.querySelector(".load-more").classList.add("visible")},g=()=>{document.querySelector(".load-more").classList.remove("visible")},d=document.querySelector(".form"),S=document.querySelector(".load-more");let l=1,i="";d.addEventListener("submit",async e=>{if(e.preventDefault(),i=d.elements["search-text"].value.trim(),!i){n.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}v(),p(),l=1;try{const r=await m(i,l);if(r.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),g();return}y(r),f()}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{h()}d.elements["search-text"].value=""});S.addEventListener("click",async()=>{l+=1,g(),p();try{const e=await m(i,l);if(e.length===0){g(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"});return}y(e),setTimeout(()=>{const r=document.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}},300),f()}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
