import{a as h,S as w,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&o(y)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const b="50757194-f2b273e514caa2f992e1a47fc",g=async(e,r=1,a=15)=>{try{return(await h.get("https://pixabay.com/api/",{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data.hits}catch(o){throw console.error("Error fetching data:",o),o}};let u;const p=e=>{const r=document.querySelector(".gallery"),a=e.map(o=>`
        <li class="gallery-item">
            <a href="${o.largeImageURL}" class="lightbox">
                <img src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class="image-info">
                <p><strong>Likes</strong> ${o.likes}</p>
                <p><strong>Views</strong> ${o.views}</p>
                <p><strong>Comments</strong> ${o.comments}</p>
                <p><strong>Downloads</strong> ${o.downloads}</p>
            </div>
        </li>
    `).join("");r.innerHTML+=a,u?u.refresh():u=new w(".gallery a",{captionsData:"alt",captionDelay:250})},L=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},m=()=>{const e=document.querySelector(".loader");e.style.display="block"},f=()=>{const e=document.querySelector(".loader");e.style.display="none"},d=document.querySelector(".form"),n=document.querySelector(".load-more");let c=1,l="";d.addEventListener("submit",async e=>{if(e.preventDefault(),l=d.elements["search-text"].value.trim(),!l){i.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}L(),m(),c=1;try{const r=await g(l,c);if(r.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n.style.display="none";return}p(r),n.style.display="block"}catch{i.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f()}d.elements["search-text"].value=""});n.addEventListener("click",async()=>{c+=1,n.style.display="none",m();try{const e=await g(l,c);if(e.length===0){n.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"});return}p(e),setTimeout(()=>{const r=document.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}},300),n.style.display="block"}catch{i.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f()}});
//# sourceMappingURL=index.js.map
