import{a as b,S as v,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const w="50757194-f2b273e514caa2f992e1a47fc",p=async(e,t=1,a=15)=>{try{return(await b.get("https://pixabay.com/api/",{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(o){throw console.error("Error fetching data:",o),o}};let d;const m=e=>{const t=document.querySelector(".gallery"),a=e.map(o=>`
        <li class="gallery-item">
            <a href="${o.largeImageURL}" class="lightbox">
                <img src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class="image-info">
                <p><strong>Likes</strong> ${o.likes}</p>
                <p><strong>Views</strong> ${o.views}</p>
                <p><strong>Comments</strong> ${o.comments}</p>
                <p><strong>Downloads</strong> ${o.downloads}</p>
            </div>
        </li>
    `).join("");t.innerHTML+=a,d?d.refresh():d=new v(".gallery a",{captionsData:"alt",captionDelay:250})},S=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},y=()=>{const e=document.querySelector(".loader");e.style.display="block"},f=()=>{const e=document.querySelector(".loader");e.style.display="none"},L=()=>{document.querySelector(".load-more").classList.add("visible")},c=()=>{document.querySelector(".load-more").classList.remove("visible")},g=document.querySelector(".form"),q=document.querySelector(".load-more"),M=document.querySelector(".search-data");let i=1,l="",h="";g.addEventListener("submit",async e=>{if(e.preventDefault(),l=g.elements["search-text"].value.trim(),!l){n.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}S(),y(),i=1;try{const t=await p(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}m(t.hits),h=`<p><strong>Search phrase</strong>: ${l}, <strong>Total imades:</strong> ${t.total}, <strong>Total hits:</strong> ${t.totalHits}, <strong>Images pp:</strong> ${t.hits.length}, <strong>Total pages:</strong> ${Math.ceil(t.totalHits/15)}</p>`,M.innerHTML=h,i*15>=t.totalHits?(c(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"})):L()}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f()}g.elements["search-text"].value=""});q.addEventListener("click",async()=>{i+=1,c(),y();try{const e=await p(l,i);if(e.hits.length===0){c(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"});return}m(e.hits),setTimeout(()=>{const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}},300),i*15>=e.totalHits?(c(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"})):L()}catch{n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f()}});
//# sourceMappingURL=index.js.map
